# Selecting Subsets of Data

In [2]:
import pandas as pd

In [4]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [5]:
%matplotlib inline

## Selecting Series data

In [6]:
# Read in the college dataset with the institution name as the index.
#select a single column as a Series with the indexing operator
college = pd.read_csv('data/college.csv', index_col='INSTNM')

In [7]:
city = college['CITY']

In [8]:
city.head()

INSTNM
Alabama A & M University                   Normal
University of Alabama at Birmingham    Birmingham
Amridge University                     Montgomery
University of Alabama in Huntsville    Huntsville
Alabama State University               Montgomery
Name: CITY, dtype: object

In [9]:
# The .iloc indexer makes selections only by integer location. 
# Passing an integer to it returns a scalar value
city.iloc[3]

'Huntsville'

In [10]:
# To select several different integer locations, pass a list to .iloc. This returns a Series
city.iloc[[10,20,30]]

INSTNM
Birmingham Southern College                            Birmingham
George C Wallace State Community College-Hanceville    Hanceville
Judson College                                             Marion
Name: CITY, dtype: object

In [11]:
# To select an equally spaced partition of data, use slice notation
city.iloc[4:50:10]

INSTNM
Alabama State University              Montgomery
Enterprise State Community College    Enterprise
Heritage Christian University           Florence
Marion Military Institute                 Marion
Reid State Technical College           Evergreen
Name: CITY, dtype: object

In [12]:
# Now we turn to the .loc indexer, which selects only with index labels. 
#Passing a single string returns a scalar value
city.loc['Heritage Christian University']

'Florence'

In [13]:
# To select several disjoint labels, use a list:
np.random.seed(1)

In [14]:
labels = list(np.random.choice(city.index, 4))

In [15]:
labels

['Northwest HVAC/R Training Center',
 'California State University-Dominguez Hills',
 'Lower Columbia College',
 'Southwest Acupuncture College-Boulder']

In [16]:
#To select an equally spaced partition of data, use slice notation.
# Make sure that the start and stop values are strings. 
# You can use an integer to specify the step size of the slice
city.loc['Alabama State University': 'Reid State Technical College':10]

INSTNM
Alabama State University              Montgomery
Enterprise State Community College    Enterprise
Heritage Christian University           Florence
Marion Military Institute                 Marion
Reid State Technical College           Evergreen
Name: CITY, dtype: object

## Selecting DataFrame rows

In [17]:
# Read in the college dataset, and set the index as the institution name
college = pd.read_csv('data/college.csv', index_col='INSTNM')

In [18]:
college.head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,4206.0,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,11383.0,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5
Amridge University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,1.0,291.0,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
Alabama State University,Montgomery,AL,1.0,0.0,0.0,0,425.0,430.0,0.0,4811.0,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5

In [19]:
#Pass an integer to the .iloc indexer to select an entire row at that position
college.iloc[60]

CITY                  Anchorage
STABBR                       AK
HBCU                          0
MENONLY                       0
WOMENONLY                     0
RELAFFIL                      0
SATVRMID                    NaN
SATMTMID                    NaN
DISTANCEONLY                  0
UGDS                      12865
UGDS_WHITE               0.5747
UGDS_BLACK               0.0358
UGDS_HISP                0.0761
UGDS_ASIAN               0.0778
UGDS_AIAN                0.0653
UGDS_NHPI                0.0086
UGDS_2MOR                 0.098
UGDS_NRA                 0.0181
UGDS_UNKN                0.0457
PPTUG_EF                 0.4539
CURROPER                      1
PCTPELL                  0.2385
PCTFLOAN                 0.2647
UG25ABV                  0.4386
MD_EARN_WNE_P10           42500
GRAD_DEBT_MDN_SUPP      19449.5
Name: University of Alaska Anchorage, dtype: object

In [20]:
# To get the same row as the preceding step, pass the index label to the .loc indexer
college.loc['University of Alaska Anchorage']

CITY                  Anchorage
STABBR                       AK
HBCU                          0
MENONLY                       0
WOMENONLY                     0
RELAFFIL                      0
SATVRMID                    NaN
SATMTMID                    NaN
DISTANCEONLY                  0
UGDS                      12865
UGDS_WHITE               0.5747
UGDS_BLACK               0.0358
UGDS_HISP                0.0761
UGDS_ASIAN               0.0778
UGDS_AIAN                0.0653
UGDS_NHPI                0.0086
UGDS_2MOR                 0.098
UGDS_NRA                 0.0181
UGDS_UNKN                0.0457
PPTUG_EF                 0.4539
CURROPER                      1
PCTPELL                  0.2385
PCTFLOAN                 0.2647
UG25ABV                  0.4386
MD_EARN_WNE_P10           42500
GRAD_DEBT_MDN_SUPP      19449.5
Name: University of Alaska Anchorage, dtype: object

In [21]:
# To select a disjointed set of rows as a DataFrame, pass a list of integers to the .iloc indexer
college.iloc[[60, 99, 3]]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
University of Alaska Anchorage,Anchorage,AK,0.0,0.0,0.0,0,NaN,NaN,0.0,12865.0,...,0.0980,0.0181,0.0457,0.4539,1,0.2385,0.2647,0.4386,42500,19449.5
International Academy of Hair Design,Tempe,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,188.0,...,0.0160,0.0000,0.0638,0.0000,0,0.7185,0.7346,0.3905,22200,10556
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097

In [22]:
# The same DataFrame from step 4 may be reproduced using .loc by passing it a list of the exact institution names
labels = ['University of Alaska Anchorage',
 'International Academy of Hair Design',
 'University of Alabama in Huntsville']

In [23]:
college.loc[labels]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
University of Alaska Anchorage,Anchorage,AK,0.0,0.0,0.0,0,NaN,NaN,0.0,12865.0,...,0.0980,0.0181,0.0457,0.4539,1,0.2385,0.2647,0.4386,42500,19449.5
International Academy of Hair Design,Tempe,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,188.0,...,0.0160,0.0000,0.0638,0.0000,0,0.7185,0.7346,0.3905,22200,10556
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097

In [24]:
# Use slice notation with .iloc to select an entire segment of the data
college.iloc[99:102]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
International Academy of Hair Design,Tempe,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,188.0,...,0.0160,0.0000,0.0638,0.0000,0,0.7185,0.7346,0.3905,22200,10556
GateWay Community College,Phoenix,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,5211.0,...,0.0127,0.0161,0.0702,0.7465,1,0.3270,0.2189,0.5832,29800,7283
Mesa Community College,Mesa,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,19055.0,...,0.0205,0.0257,0.0682,0.6457,1,0.3423,0.2207,0.4010,35200,8000

In [25]:
# Slice notation also works with the .loc indexer and is inclusive of the last label
start = 'International Academy of Hair Design'

In [26]:
stop = 'Mesa Community College'

In [27]:
college.loc[start:stop]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
International Academy of Hair Design,Tempe,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,188.0,...,0.0160,0.0000,0.0638,0.0000,0,0.7185,0.7346,0.3905,22200,10556
GateWay Community College,Phoenix,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,5211.0,...,0.0127,0.0161,0.0702,0.7465,1,0.3270,0.2189,0.5832,29800,7283
Mesa Community College,Mesa,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,19055.0,...,0.0205,0.0257,0.0682,0.6457,1,0.3423,0.2207,0.4010,35200,8000

## Selecting DataFrame rows and columns simultaneously

- Directly using the indexing operator is the correct method to select one or more columns from a DataFrame
- To select rows and columns simultaneously, you will need to pass both valid row and column selections separated by a comma to either the .iloc or .loc indexers.

In [28]:
# Read in the college dataset, and set the index as the institution name. 
#Select the first three rows and the first four columns with slice notation
college = pd.read_csv('data/college.csv', index_col='INSTNM')

In [29]:
college.iloc[:3, :4]

                                           CITY STABBR  HBCU  MENONLY
INSTNM
Alabama A & M University                 Normal     AL   1.0      0.0
University of Alabama at Birmingham  Birmingham     AL   0.0      0.0
Amridge University                   Montgomery     AL   0.0      0.0

In [30]:
college.loc[:'Amridge University', :'MENONLY']

                                           CITY STABBR  HBCU  MENONLY
INSTNM
Alabama A & M University                 Normal     AL   1.0      0.0
University of Alabama at Birmingham  Birmingham     AL   0.0      0.0
Amridge University                   Montgomery     AL   0.0      0.0

In [31]:
# Select all the rows of two different columns
college.iloc[:, [4,6]].head()

                                     WOMENONLY  SATVRMID
INSTNM
Alabama A & M University                   0.0     424.0
University of Alabama at Birmingham        0.0     570.0
Amridge University                         0.0       NaN
University of Alabama in Huntsville        0.0     595.0
Alabama State University                   0.0     425.0

In [32]:
college.loc[:, ['WOMENONLY', 'SATVRMID']].head()

                                     WOMENONLY  SATVRMID
INSTNM
Alabama A & M University                   0.0     424.0
University of Alabama at Birmingham        0.0     570.0
Amridge University                         0.0       NaN
University of Alabama in Huntsville        0.0     595.0
Alabama State University                   0.0     425.0

In [33]:
# Select disjointed rows and columns
college.iloc[[100, 200], [7, 15]]

                                       SATMTMID  UGDS_NHPI
INSTNM
GateWay Community College                   NaN     0.0029
American Baptist Seminary of the West       NaN        NaN

In [34]:
 rows = ['GateWay Community College', 'American Baptist Seminary of the West']

In [35]:
columns = ['SATMTMID', 'UGDS_NHPI']

In [36]:
college.loc[rows, columns]

                                       SATMTMID  UGDS_NHPI
INSTNM
GateWay Community College                   NaN     0.0029
American Baptist Seminary of the West       NaN        NaN

In [37]:
# Select a single scalar value
college.iloc[5, -4]

0.401

In [38]:
college.loc['The University of Alabama', 'PCTFLOAN']

0.401

In [39]:
# Slice the rows and select a single column
college.iloc[90:80:-2, 5]

INSTNM
Empire Beauty School-Flagstaff     0
Charles of Italy Beauty College    0
Central Arizona College            0
University of Arizona              0
Arizona State University-Tempe     0
Name: RELAFFIL, dtype: int64

In [40]:
start = 'Empire Beauty School-Flagstaff'

In [41]:
stop = 'Arizona State University-Tempe'

In [42]:
college.loc[start:stop:-2, 'RELAFFIL']

INSTNM
Empire Beauty School-Flagstaff     0
Charles of Italy Beauty College    0
Central Arizona College            0
University of Arizona              0
Arizona State University-Tempe     0
Name: RELAFFIL, dtype: int64

## Selecting data with both integers and labels

In [43]:
# Read in the college dataset and assign the institution name (INSTNM) as the index
college = pd.read_csv('data/college.csv', index_col='INSTNM')

In [44]:
#Use the Index method get_loc to find the integer position of the desired columns
col_start = college.columns.get_loc('UGDS_WHITE')

In [45]:
col_end = college.columns.get_loc('UGDS_UNKN') + 1

In [46]:
col_start, col_end

(10, 19)

In [47]:
# Use col_start and col_end to select columns by integer location using .iloc
college.iloc[:5, col_start:col_end]

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137

## Speeding up scalar selection

In [48]:
#Read in the college scoreboard dataset with the institution name as the index.
#Pass a college name and column name to .loc in order to select a scalar value
college = pd.read_csv('data/college.csv', index_col='INSTNM')

In [49]:
cn = 'Texas A & M University-College Station'

In [50]:
college.loc[cn, 'UGDS_WHITE']

0.6609999999999999

In [51]:
#Achieve the same result with .at
college.at[cn, 'UGDS_WHITE']

0.6609999999999999

In [52]:
# Use the %timeit magic command to find the difference in speed
%timeit college.loc[cn, 'UGDS_WHITE']

10.5 µs ± 571 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [53]:
%timeit college.at[cn, 'UGDS_WHITE']

6.55 µs ± 516 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [54]:
# Find the integer locations of the preceding selections and then time the difference between .iloc and .iat
row_num = college.index.get_loc(cn)

In [55]:
col_num = college.columns.get_loc('UGDS_WHITE')

In [56]:
row_num, col_num

(3765, 10)

In [57]:
%timeit college.iloc[row_num, col_num]

11.3 µs ± 562 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [58]:
%timeit college.iat[row_num, col_num]

6.47 µs ± 596 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

## Slicing rows lazily

In [59]:
# Read in the college dataset with the institution name as the index and then select every other row from index 10 to 20
college = pd.read_csv('data/college.csv', index_col='INSTNM')

In [60]:
college[10:20:2]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Birmingham Southern College,Birmingham,AL,0.0,0.0,0.0,1,560.0,560.0,0.0,1180.0,...,0.0051,0.0000,0.0051,0.0017,1,0.1920,0.4809,0.0152,44200,27000
Concordia College Alabama,Selma,AL,1.0,0.0,0.0,1,420.0,400.0,0.0,322.0,...,0.0031,0.0466,0.0000,0.1056,1,0.8667,0.9333,0.2367,19900,PrivacySuppressed
Enterprise State Community College,Enterprise,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,1729.0,...,0.0254,0.0012,0.0069,0.3823,1,0.4895,0.2263,0.3399,24600,8273
Faulkner University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,0.0,2367.0,...,0.0173,0.0182,0.0258,0.2302,1,0.5812,0.7253,0.4589,37200,22000
New Beginning College of Cosmetology,Albertville,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,115.0,...,0.0000,0.0000,0.0000,0.0783,1,0.8224,0.8553,0.3933,NaN,5500

In [61]:
# This same slicing exists with Series
city = college['CITY']

In [62]:
city[10:20:2]

INSTNM
Birmingham Southern College              Birmingham
Concordia College Alabama                     Selma
Enterprise State Community College       Enterprise
Faulkner University                      Montgomery
New Beginning College of Cosmetology    Albertville
Name: CITY, dtype: object

In [63]:
#Both Series and DataFrames can slice by label as well with just the indexing operator
start = 'Mesa Community College'

In [64]:
stop = 'Spokane Community College'

In [65]:
college[start:stop:1500]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Mesa Community College,Mesa,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,19055.0,...,0.0205,0.0257,0.0682,0.6457,1,0.3423,0.2207,0.4010,35200,8000
Hair Academy Inc-New Carrollton,New Carrollton,MD,0.0,0.0,0.0,0,NaN,NaN,0.0,504.0,...,0.0000,0.0000,0.0000,0.4683,1,0.9756,1.0000,0.5882,15200,9666
National College of Natural Medicine,Portland,OR,0.0,0.0,0.0,0,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,PrivacySuppressed

In [66]:
# Here is the same slice by label with a Series
city[start:stop:1500]

INSTNM
Mesa Community College                            Mesa
Hair Academy Inc-New Carrollton         New Carrollton
National College of Natural Medicine          Portland
Name: CITY, dtype: object

## Slicing lexicographically

In [67]:
# Read in the college dataset, and set the institution name as the index
college = pd.read_csv('data/college.csv', index_col='INSTNM')

In [69]:
#sort the index
college = college.sort_index()

In [70]:
#  select all colleges with names lexicographically between 'Sp' and 'Su'
college.loc['Sp':'Su']

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Spa Tech Institute-Ipswich,Ipswich,MA,0.0,0.0,0.0,0,NaN,NaN,0.0,37.0,...,0.0000,0.0000,0.0541,0.4054,1,0.2656,0.3906,0.7907,21500,6333
Spa Tech Institute-Plymouth,Plymouth,MA,0.0,0.0,0.0,0,NaN,NaN,0.0,153.0,...,0.0000,0.0000,0.2484,0.3399,1,0.3716,0.4266,0.6250,21500,6333
Spa Tech Institute-Westboro,Westboro,MA,0.0,0.0,0.0,0,NaN,NaN,0.0,90.0,...,0.0000,0.0000,0.0222,0.5778,1,0.3409,0.4545,0.6882,21500,6333
Spa Tech Institute-Westbrook,Westbrook,ME,0.0,0.0,0.0,0,NaN,NaN,0.0,240.0,...,0.0000,0.0000,0.0042,0.2542,1,0.4350,0.5093,0.5224,21500,6333
Spalding University,Louisville,KY,0.0,0.0,0.0,1,490.0,440.0,0.0,1227.0,...,0.0302,0.0016,0.0326,0.2502,1,0.4442,0.6725,0.3764,41700,25000
Spanish-American Institute,New York,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,0.0,...,0.0000,0.0000,0.0000,NaN,1,NaN,NaN,0.8667,19700,NaN
Spartan College of Aeronautics & Technology,Inglewood,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,414.0,...,0.0000,0.0048,0.0531,0.0000,1,0.7507,0.7698,0.5066,41000,24059
Spartan College of Aeronautics and Technology,Tulsa,OK,0.0,0.0,0.0,0,NaN,NaN,0.0,849.0,...,0.0978,0.0118,0.0106,0.0000,1,0.8592,0.9547,0.3843,39300,18018.5
Spartanburg Community College,Spartanburg,SC,0.0,0.0,0.0,0,NaN,NaN,0.0,4694.0,...,0.0245,0.0002,0.0109,0.4495,1,0.5409,0.1414,0.3380,25500,4500
Spartanburg Methodist College,Spartanburg,SC,0.0,0.0,0.0,1,430.0,440.0,0.0,790.0,...,0.0152,0.0076,0.0000,0.0177,1,0.5098,0.6614,0.0134,28400,12000
Specs Howard School of Media Arts,Southfield,MI,0.0,0.0,0.0,0,NaN,NaN,0.0,653.0,...,0.0153,0.0000,0.0015,1.0000,1,0.4390,0.6821,0.4003,27200,11370
Spelman College,Atlanta,GA,1.0,0.0,1.0,0,510.0,490.0,0.0,2135.0,...,0.0272,0.0150,0.0829,0.0295,1,0.4777,0.7172,0.0254,46000,26996
Spencerian College-Lexington,Lexington,KY,0.0,0.0,0.0,0,NaN,NaN,0.0,99.0,...,0.1212,0.0000,0.0303,0.2727,1,0.7233,0.7044,0.5660,31600,17357
Spencerian College-Louisville,Louisville,KY,0.0,0.0,0.0,0,NaN,NaN,0.0,467.0,...,0.1006,0.0000,0.0257,0.3854,1,0.6041,0.6360,0.5722,31600,17357
Spertus College,Chicago,IL,0.0,0.0,0.0,0,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,PrivacySuppressed
Spokane Community College,Spokane,WA,0.0,0.0,0.0,0,NaN,NaN,0.0,4982.0,...,0.0552,0.0032,0.0566,0.2708,1,0.5160,0.3901,0.5325,31100,16750
Spokane Falls Community College,Spokane,WA,0.0,0.0,0.0,0,NaN,NaN,0.0,4650.0,...,0.0725,0.0174,0.0355,0.2424,1,0.2803,0.1747,0.5083,28700,10614
Spoon River College,Canton,IL,0.0,0.0,0.0,0,NaN,NaN,0.0,1160.0,...,0.0026,0.0009,0.0000,0.3733,1,0.3184,0.1553,0.3167,28000,PrivacySuppressed
Spring Arbor University,Spring Arbor,MI,0.0,0.0,0.0,1,525.0,568.0,0.0,2632.0,...,0.0217,0.0080,0.0593,0.2819,1,0.4544,0.7518,0.4562,38100,25000
Spring Hill College,Mobile,AL,0.0,0.0,0.0,1,535.0,538.0,0.0,1215.0,...,0.0346,0.0222,0.0337,0.0305,1,0.2307,0.6873,0.0712,42800,27000
Springfield Beauty Academy,Annandale,VA,0.0,0.0,0.0,0,NaN,NaN,0.0,57.0,...,0.0000,0.0000,0.0175,0.2281,1,1.0000,0.8800,0.8228,19300,5371
Springfield College,Springfield,MA,0.0,0.0,0.0,0,510.0,530.0,0.0,2136.0,...,0.0150,0.0234,0.0225,0.0131,1,0.2336,0.8020,0.0202,43800,24826.5
Springfield College of Beauty,Springfield,OR,0.0,0.0,0.0,0,NaN,NaN,0.0,71.0,...,0.0704,0.0000,0.0000,0.0000,1,0.7154,0.6911,0.5072,14000,14645
Springfield College-School of Professional and Continuing Studies,Springfield,MA,0.0,0.0,0.0,0,NaN,NaN,0.0,1237.0,...,0.0226,0.0032,0.0251,0.3444,1,0.7375,0.9194,0.9636,43800,24826.5
Springfield Technical Community College,Springfield,MA,0.0,0.0,0.0,0,NaN,NaN,0.0,6069.0,...,0.0201,0.0082,0.0058,0.5001,1,0.5618,0.2462,0.4282,30300,5761
St Andrews University,Laurinburg,NC,0.0,0.0,0.0,1,480.0,460.0,0.0,601.0,...,0.0216,0.1082,0.1647,0.0682,1,0.4269,0.7429,0.1126,34800,21562
St Bernard's School of Theology and Ministry,Rochester,NY,0.0,0.0,0.0,1,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,PrivacySuppressed
St Bonaventure University,Saint Bonaventure,NY,0.0,0.0,0.0,1,525.0,525.0,0.0,1735.0,...,0.0173,0.0173,0.1003,0.0098,1,0.2941,0.6977,0.0246,44100,27000
St Catherine University,Saint Paul,MN,0.0,0.0,1.0,1,548.0,547.0,0.0,3399.0,...,0.0224,0.0091,0.0380,0.3869,1,0.3990,0.7527,0.3830,45000,28065
St Charles Community College,Cottleville,MO,0.0,0.0,0.0,0,NaN,NaN,0.0,6565.0,...,0.0331,0.0084,0.0373,0.4859,1,0.2394,0.1061,0.2847,32300,8508.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Strayer University-Pennsylvania,Trevose,PA,0.0,0.0,0.0,0,NaN,NaN,0.0,1537.0,...,0.0208,0.0026,0.0390,0.8972,1,0.4873,0.6031,0.8115,49200,36173.5
Strayer University-Piscataway,Piscataway,NJ,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
Strayer University-Plano,Plano,TX,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
Strayer University-Rockville Campus,Rockville,MD,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
Strayer University-Roswell Campus,Roswell,GA,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
Strayer University-San Antonio,San Antonio,TX,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,36173.5
Strayer University-Sand Lake Campus,Orlando,FL,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
Strayer University-Savannah Campus,Savannah,GA,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
Strayer University-Shelby Oaks Campus,Memphis,TN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
Strayer University-South Carolina,Greenville,SC,0.0,0.0,0.0,0,NaN,NaN,0.0,1206.0,...,0.0199,0.0008,0.0348,0.8698,1,0.5347,0.5969,0.8559,49200,36173.5
Strayer University-South Charlotte,Charlotte,NC,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
Strayer University-South Raleigh Campus,Raleigh,NC,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
Strayer University-Stafford,Stafford,TX,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,36173.5
Strayer University-Takoma Park Campus,Washington,DC,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
Strayer University-Tampa East Campus,Tampa,FL,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
Strayer University-Tennessee,Memphis,TN,0.0,0.0,0.0,0,NaN,NaN,0.0,1273.0,...,0.0196,0.0024,0.0181,0.9262,1,0.5551,0.6414,0.8386,49200,36173.5
Strayer University-Texas,Austin,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,1217.0,...,0.0353,0.0041,0.0345,0.8250,1,0.5046,0.6049,0.8989,49200,36173.5
Strayer University-Virginia,Arlington,VA,0.0,0.0,0.0,0,NaN,NaN,0.0,4448.0,...,0.0313,0.0171,0.0441,0.7214,1,0.2993,0.4036,0.8871,49200,36173.5
Strayer University-Virginia Beach Campus,Virginia Beach,VA,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
Strayer University-Warrendale Campus,Warrendale,PA,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
Strayer University-West Virginia,Scott Depot,WV,0.0,0.0,0.0,0,NaN,NaN,0.0,156.0,...,0.0256,0.0000,0.0128,0.9167,1,0.5989,0.6780,0.7627,49200,36173.5
Strayer University-White Marsh Campus,Baltimore,MD,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
Strayer University-Willingboro Campus,Willingboro,NJ,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
Strayer University-Woodbridge Campus,Woodbridge,VA,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
Stroudsburg School of Cosmetology,Stroudsburg,PA,0.0,0.0,0.0,0,NaN,NaN,0.0,45.0,...,0.0000,0.0000,0.0000,0.1111,1,0.5732,0.6707,0.4545,12200,11295
Studio Academy of Beauty,Chandler,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,332.0,...,0.0392,0.0000,0.0090,0.0000,1,0.5855,0.6218,0.5675,NaN,6333
Studio Jewelers,New York,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,55.0,...,0.0000,0.0364,0.0000,0.6000,1,0.0451,0.0902,0.8525,PrivacySuppressed,PrivacySuppressed
Stylemaster College of Hair Design,Longview,WA,0.0,0.0,0.0,0,NaN,NaN,0.0,77.0,...,0.0130,0.0000,0.0000,0.0000,1,0.8036,0.7024,0.4510,17000,13320
Styles and Profiles Beauty College,Selmer,TN,0.0,0.0,0.0,0,NaN,NaN,0.0,31.0,...,0.0000,0.0000,0.0000,0.0000,1,0.8182,0.7955,0.2400,PrivacySuppressed,PrivacySuppressed
Styletrends Barber and Hairstyling Academy,Rock Hill,SC,0.0,0.0,0.0,0,NaN,NaN,0.0,45.0,...,0.0000,0.0000,0.0000,0.5556,0,1.0000,1.0000,0.3529,PrivacySuppressed,9495.5